services:
  edge-agent:
    image: ${EDGE_AGENT_IMAGE}
    container_name: edge-agent
    network_mode: host
    restart: always

    environment:
      CONFIG_FILE: prod
      FLEET_CONTROLLER_URL: http://78.187.40.81:12000

    volumes:
      - /etc/hostname:/etc/hostname:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./state:/app/state
      - ./logs:/app/logs