version: "3.9"

services:
  scoreboard:
    image: ghcr.io/bncool/stream-score/scoreboard:latest
    container_name: scoreboard
    restart: always
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

# docker compose -f docker-compose-prod.yml pull
# docker compose -f docker-compose-prod.yml up -d